package com.nimba.creditcase

/**
 * The pieces that constitute a credit case's dossier. TA and FA are built by the
 * DRI during constitution; PV, FMP and NOTIFICATION are generated later in the
 * workflow (PV once the comité approves, FMP/NOTIFICATION from the PV) — see
 * `CaseTypePolicy`.
 */
enum class DocumentKind {
    /** Tableau d'amortissement — the amortization schedule, uploaded first. */
    TA,

    /** Fiche d'analyse — the structured analysis sheet, drafted from the TA. */
    FA,

    /** Procès-verbal — generated by DCM once the comité approves the dossier. */
    PV,

    /** Fiche de mise en place — generated from the PV. */
    FMP,

    /** Notification de crédit — generated from the PV. */
    NOTIFICATION,
}
