package com.nimba.client.internal

import com.nimba.client.ClientInfo
import com.nimba.client.ClientType
import com.nimba.client.CreateClientCommand
import com.nimba.client.UpdateClientCommand
import jakarta.validation.constraints.NotBlank
import jakarta.validation.constraints.Size
import java.time.Instant
import java.time.LocalDate
import java.util.UUID

/**
 * Create payload. [matricule] is entered once and never editable afterward —
 * see [Client]'s KDoc for why it isn't generated by Nimba.
 */
data class CreateClientRequest(
    @field:Size(max = 50, message = "50 caractères maximum")
    val matricule: String? = null,
    val type: ClientType = ClientType.ENTREPRISE,
    @field:NotBlank
    @field:Size(min = 1, max = 200, message = "Le nom du client doit faire entre 1 et 200 caractères")
    val raisonSociale: String,
    @field:Size(max = 100, message = "100 caractères maximum")
    val sigle: String? = null,
    @field:Size(max = 100, message = "100 caractères maximum")
    val formeJuridique: String? = null,
    val dateCreation: LocalDate? = null,
    @field:Size(max = 300, message = "300 caractères maximum")
    val adressePhysique: String? = null,
    @field:Size(max = 300, message = "300 caractères maximum")
    val activiteDeBase: String? = null,
    @field:Size(max = 50, message = "50 caractères maximum")
    val codeNif: String? = null,
    @field:Size(max = 50, message = "50 caractères maximum")
    val rccm: String? = null,
    @field:Size(max = 50, message = "50 caractères maximum")
    val accountNumber: String? = null,
    @field:Size(max = 200, message = "200 caractères maximum")
    val principalDirigeant: String? = null,
    val dateEntreeRelation: LocalDate? = null,
    val dateDerniereVisite: LocalDate? = null,
    @field:Size(max = 100, message = "100 caractères maximum")
    val agence: String? = null,
    @field:Size(max = 200, message = "200 caractères maximum")
    val gestionnaire: String? = null,
    @field:Size(max = 200, message = "200 caractères maximum")
    val analyste: String? = null,
    @field:Size(max = 20, message = "20 caractères maximum")
    val cotationPrecedente: String? = null,
    @field:Size(max = 20, message = "20 caractères maximum")
    val cotationActuelle: String? = null,
)

internal fun CreateClientRequest.toCommand(createdBy: UUID): CreateClientCommand =
    CreateClientCommand(
        matricule = matricule?.takeIf { it.isNotBlank() },
        type = type,
        raisonSociale = raisonSociale,
        createdBy = createdBy,
        sigle = sigle,
        formeJuridique = formeJuridique,
        dateCreation = dateCreation,
        adressePhysique = adressePhysique,
        activiteDeBase = activiteDeBase,
        codeNif = codeNif,
        rccm = rccm,
        accountNumber = accountNumber,
        principalDirigeant = principalDirigeant,
        dateEntreeRelation = dateEntreeRelation,
        dateDerniereVisite = dateDerniereVisite,
        agence = agence,
        gestionnaire = gestionnaire,
        analyste = analyste,
        cotationPrecedente = cotationPrecedente,
        cotationActuelle = cotationActuelle,
    )

/** Update payload — same fields as [CreateClientRequest] minus [CreateClientRequest.matricule]. */
data class UpdateClientRequest(
    @field:NotBlank
    @field:Size(min = 1, max = 200, message = "Le nom du client doit faire entre 1 et 200 caractères")
    val raisonSociale: String,
    @field:Size(max = 100, message = "100 caractères maximum")
    val sigle: String? = null,
    @field:Size(max = 100, message = "100 caractères maximum")
    val formeJuridique: String? = null,
    val dateCreation: LocalDate? = null,
    @field:Size(max = 300, message = "300 caractères maximum")
    val adressePhysique: String? = null,
    @field:Size(max = 300, message = "300 caractères maximum")
    val activiteDeBase: String? = null,
    @field:Size(max = 50, message = "50 caractères maximum")
    val codeNif: String? = null,
    @field:Size(max = 50, message = "50 caractères maximum")
    val rccm: String? = null,
    @field:Size(max = 50, message = "50 caractères maximum")
    val accountNumber: String? = null,
    @field:Size(max = 200, message = "200 caractères maximum")
    val principalDirigeant: String? = null,
    val dateEntreeRelation: LocalDate? = null,
    val dateDerniereVisite: LocalDate? = null,
    @field:Size(max = 100, message = "100 caractères maximum")
    val agence: String? = null,
    @field:Size(max = 200, message = "200 caractères maximum")
    val gestionnaire: String? = null,
    @field:Size(max = 200, message = "200 caractères maximum")
    val analyste: String? = null,
    @field:Size(max = 20, message = "20 caractères maximum")
    val cotationPrecedente: String? = null,
    @field:Size(max = 20, message = "20 caractères maximum")
    val cotationActuelle: String? = null,
)

internal fun UpdateClientRequest.toCommand(): UpdateClientCommand =
    UpdateClientCommand(
        raisonSociale = raisonSociale,
        sigle = sigle,
        formeJuridique = formeJuridique,
        dateCreation = dateCreation,
        adressePhysique = adressePhysique,
        activiteDeBase = activiteDeBase,
        codeNif = codeNif,
        rccm = rccm,
        accountNumber = accountNumber,
        principalDirigeant = principalDirigeant,
        dateEntreeRelation = dateEntreeRelation,
        dateDerniereVisite = dateDerniereVisite,
        agence = agence,
        gestionnaire = gestionnaire,
        analyste = analyste,
        cotationPrecedente = cotationPrecedente,
        cotationActuelle = cotationActuelle,
    )

data class ClientResponse(
    val id: UUID,
    val type: ClientType,
    val matricule: String?,
    val raisonSociale: String,
    val sigle: String?,
    val formeJuridique: String?,
    val dateCreation: LocalDate?,
    val adressePhysique: String?,
    val activiteDeBase: String?,
    val codeNif: String?,
    val rccm: String?,
    val accountNumber: String?,
    val principalDirigeant: String?,
    val dateEntreeRelation: LocalDate?,
    val dateDerniereVisite: LocalDate?,
    val agence: String?,
    val gestionnaire: String?,
    val analyste: String?,
    val cotationPrecedente: String?,
    val cotationActuelle: String?,
    val createdAt: Instant,
    val updatedAt: Instant,
)

internal fun ClientInfo.toResponse(): ClientResponse =
    ClientResponse(
        id = id,
        type = type,
        matricule = matricule,
        raisonSociale = raisonSociale,
        sigle = sigle,
        formeJuridique = formeJuridique,
        dateCreation = dateCreation,
        adressePhysique = adressePhysique,
        activiteDeBase = activiteDeBase,
        codeNif = codeNif,
        rccm = rccm,
        accountNumber = accountNumber,
        principalDirigeant = principalDirigeant,
        dateEntreeRelation = dateEntreeRelation,
        dateDerniereVisite = dateDerniereVisite,
        agence = agence,
        gestionnaire = gestionnaire,
        analyste = analyste,
        cotationPrecedente = cotationPrecedente,
        cotationActuelle = cotationActuelle,
        createdAt = createdAt,
        updatedAt = updatedAt,
    )

/** Row in the Cautions workspace's client picker/list. */
data class ClientSummaryResponse(
    val id: UUID,
    val type: ClientType,
    val matricule: String?,
    val raisonSociale: String,
    val agence: String?,
)

internal fun ClientInfo.toSummaryResponse(): ClientSummaryResponse =
    ClientSummaryResponse(
        id = id,
        type = type,
        matricule = matricule,
        raisonSociale = raisonSociale,
        agence = agence,
    )
