-- Client registry (NIMBA-75), independent of credit_case: the Caution
-- module's documents (SMS, ACF, later AVD...) must be grouped reliably by
-- matricule even for a company that never has a leasing dossier. matricule
-- is the bank's own pre-existing internal client code, entered by DCM, not
-- generated by Nimba.
CREATE TABLE client (
    id                    UUID         PRIMARY KEY,
    matricule             VARCHAR(50)  NOT NULL,
    raison_sociale        VARCHAR(200) NOT NULL,
    sigle                 VARCHAR(100),
    forme_juridique       VARCHAR(100),
    date_creation         DATE,
    adresse_physique      VARCHAR(300),
    activite_de_base      VARCHAR(300),
    code_nif              VARCHAR(50),
    rccm                  VARCHAR(50),
    account_number        VARCHAR(50),
    principal_dirigeant   VARCHAR(200),
    date_entree_relation  DATE,
    date_derniere_visite  DATE,
    agence                VARCHAR(100),
    gestionnaire          VARCHAR(200),
    analyste              VARCHAR(200),
    cotation_precedente   VARCHAR(20),
    cotation_actuelle     VARCHAR(20),
    created_by            UUID         NOT NULL,
    created_at            TIMESTAMPTZ  NOT NULL,
    updated_at            TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_client_matricule UNIQUE (matricule)
);
